Revert "Minor cleanup pt 2." (#69)
Reverts NovaSky-AI/SkyRL#67

Users are getting errors with the update to `_init_tool_groups` (from
`init_tool_groups`) related to fixed skyrl-gym. Will revert this and
fix.

```
File "/tmp/ray/session_2025-07-08_01-27-39_405126_2918156/runtime_resources/working_dir_files/_ray_pkg_32090e37b3aa13c5/examples/exp/search/env.py", line 31, in
 __init__
    self._init_tool_groups([self.tool_group])
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExpSearchEnv' object has no attribute '_init_tool_groups'. Did you mean: 'init_tool_groups'?. Did you mean: '_return_value'?
```