[tiny fix] Remove the example launch command for main files (#268)
This PR deletes the examples `uv run ...` launch commands added to the
top of many `main` files.

A few users have hit a mysterious `uv` error, and I learned it's because
they were using the default command in `main_base.py`, which is
incorrect. Here was the error:

```
AssertionError: uv run command [] is not a suffix of command line ['uv', 'run', '--isolated', '--extra', 'vllm', '--extra', 'sandboxes', '-m', 'examples.terminal_bench.main_tbench_generate']
```

Users shouldn't actually run these commands directly, it's much much
better to go through a `.sh` file in the examples.

---------

Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>